### ISSUE TITLE
Provide musl build

### ISSUE THREAD

**Issue by blacklightpy** [Giuliopime/ZenBreak#22]
This will make the build available for musl libc (make it with DeepSeek, I don't know how to work with gradle and conveyor to pack both glibc and musl builds).

```YAML
      - name: Install musl and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build jar with musl
        run: |
          export CC=musl-gcc
          ./gradlew jar
```

Alternatively, you could export `CFLAGS="-static"` and `LDFLAGS="-static"` to make a static build, and static builds made with musl will also work in glibc systems, but with an increased filesize. Static builds made with glibc won't work on musl though.

But Flatpak should solve the problem too. Since musl systems are a minority (Void, Alpine, Gentoo), usually musl releases are made downstream.
